; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Mon Aug 29 2022 21:37:15 GMT+0100 (Western European Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


