; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Mon Aug 29 2022 21:37:16 GMT+0100 (Western European Summer Time)
M280 P0 S10 ; deploy BLTouch

