; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Mon Aug 29 2022 21:37:18 GMT+0100 (Western European Summer Time)

