; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Mon Aug 29 2022 21:37:18 GMT+0100 (Western European Summer Time)
; Wait for set temperatures to be reached
M116 P0

